import argparse
import itertools
import json

def main(data_path, output_path):
    print(f"Reading DIMSUM data from file at: {data_path}")
    dimsum_jsonl = []

    with open(data_path, "r") as data_file:
        # Group into alternative divider / sentence chunks.
        for is_divider, lines in itertools.groupby(data_file, _is_divider):
            # Ignore the divider chunks, so that `lines` corresponds to the words
            # of a single sentence.
            if not is_divider:
                fields = [line.strip().split() for line in lines]
                fields = [list(field) for field in zip(*fields)]
                tokens = fields[1]
                lemmas = fields[2]
                upos_tags = ["CCONJ" if x == "CONJ" else x for x in fields[3]]
                assert len(lemmas) == len(upos_tags)
                # copulas were tagged as VERB in UDv1 (dimsum tagset) but are AUX in UDv2.
                for idx in range(len(upos_tags)):
                    if lemmas[idx] == "be" and upos_tags[idx] == "VERB":
                        upos_tags[idx] = "AUX"
                dimsum_jsonl.append({
                    "tokens": tokens,
                    "upos_tags": upos_tags,
                    "lemmas": lemmas
                })

    print(f"Writing output to {output_path}")
    with open(output_path, "w") as output_file:
        for example in dimsum_jsonl:
            output_file.write(f"{json.dumps(example)}\n")

def _is_divider(line: str) -> bool:
    return line.strip() == ""

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=("Convert a DIMSUM data file into a jsonl file suitable as "
                     "input for prediction."),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--data-path", required=True,
                        help="Path to the DIMSUM data file.")
    parser.add_argument("--output-path", required=True,
                        help=("Path to write output jsonl generated by "
                              "DIMSUM data file."))
    args = parser.parse_args()
    main(args.data_path, args.output_path)
