import argparse
import json
from conllu import parse_incr


def main(data_path, output_path):
    print(f"Reading PARSEME data from file at: {data_path}")
    parseme_jsonl = []

    with open(data_path, "r") as conllu_file:
        for annotation in parse_incr(conllu_file):
            tokens = [x["form"] for x in annotation]
            lemmas = [x["lemma"] for x in annotation]
            upos_tags = [x["upostag"] for x in annotation]

            parseme_jsonl.append({
                "tokens": tokens,
                "upos_tags": upos_tags,
                "lemmas": lemmas
            })

    print(f"Writing output to {output_path}")
    with open(output_path, "w") as output_file:
        for example in parseme_jsonl:
            output_file.write(f"{json.dumps(example)}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=("Convert a PARSEME data file into a jsonl file suitable as "
                     "input for prediction."),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--data-path", required=True,
                        help="Path to the PARSEME data file.")
    parser.add_argument("--output-path", required=True,
                        help=("Path to write output jsonl generated by "
                              "PARSEME data file."))
    args = parser.parse_args()
    main(args.data_path, args.output_path)
